name: CI
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake make gcc g++ \
            libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev git

      - name: Setup raylib
        run: |
          cd third_party
          git clone --depth=1 --branch 5.0 https://github.com/raysan5/raylib.git

      - name: Build (desktop)
        run: |
          cmake -B build -S .
          cmake --build build -j

      - name: Tests
        run: |
          cmake -B build-tests -S tests
          cmake --build build-tests -j
          ./build-tests/ascendancy_tests
