name: CI
on: [push, pull_request]
jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake make gcc g++ \
            libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev git

      - name: Setup raylib
  run: |
    mkdir -p third_party
    rm -rf third_party/raylib
    git clone --depth=1 --branch 5.0 https://github.com/raysan5/raylib.git third_party/raylib
